import type { Metadata } from "next";

import "./globals.css";
 import { Viaoda_Libre } from "next/font/google";

const viaoda = Viaoda_Libre({
  subsets: ["latin"],
  variable: "--font-viaoda",
  weight:"400"
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${viaoda.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
