import type { Metadata } from "next";

import "./globals.css";
import { Quicksand } from "next/font/google";
import Navbar from "../components/Navbar";

const quickSand = Quicksand({
  subsets: ["latin"],
  variable: "--font-viaoda",
    
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${quickSand.className} antialiased w-screen flex flex-col items-center bg-[#F5EFE8] text-[#3e2c1c]  min-h-screen`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
